### PR TITLE
Update of FRENCH translation for About us extension

### PR DESCRIPTION
**Pull request by Galixte**
Hi @Crizz0,

could you merge this, please ?

### CODE REVIEW

**Comment by Crizz0** [comment]
Why do you change the file header? Now it is different to all others.

**Comment by Galixte** [comment]
Hi,

I correct the incorrect header file that I had forgotten to recommend to you the last time I did share some information to modify: https://github.com/Crizz0/phpbb3-about-us/pull/26#discussion-diff-32884891.

All official extensions use the same header file, look:
- https://github.com/phpbb-extensions/pages/blob/master/language/en/exceptions.php
  - my french translaton: https://github.com/phpbb-extensions/pages/blob/master/language/fr/exceptions.php
- https://github.com/phpbb-extensions/boardrules/blob/master/language/en/boardrules_acp.php
  - my french translaton: https://github.com/phpbb-extensions/boardrules/blob/master/language/fr/boardrules_acp.php
- https://github.com/phpbb-extensions/autogroups/blob/release-1.0.1/language/en/autogroups_acp.php
  - my french translaton: https://github.com/phpbb-extensions/autogroups/blob/release-1.0.1/language/fr/autogroups_acp.php
- https://github.com/phpbb-extensions/boardannouncements/blob/master/language/en/boardannouncements_acp.php
  - my french translaton: https://github.com/phpbb-extensions/boardannouncements/blob/master/language/fr/boardannouncements_acp.php

**Comment by Crizz0** [comment]
If  i will change the header, i will change all at once. But i will not have one different from the other. So please provide the old one in that PR.

**Comment by Galixte** [comment]
It takes five minute to doing a new PR to make that, do you want that i do for you ?

**Comment by Crizz0** [comment]
No. I will do this to meet the latest 3.1. coding guidelines, when all language files are updated.

**Pull request merged**
