### PR TITLE
Brazilian Portuguese translation ADD and update

### PR DESCRIPTION
**Pull request by eunaumtenhoid**

### CODE REVIEW

**Comment by Crizz0** [comment]
Please solve the errors:
`Fatal error: Detected windows style newlines instead of UNIX newlines in /language/pt_br/common.php`

**Comment by eunaumtenhoid** [comment]
hummm?

**Comment by Crizz0** [comment]
How can I help you?

**Comment by eunaumtenhoid** [comment]
What is the problem, I did not understand?

**Comment by Crizz0** [comment]
Your new language file has the wrong line endings: https://youtu.be/x36T7Ebzd78

Please convert them to Unix (LF)

**Comment by eunaumtenhoid** [comment]
because? I just translate on top of the English file

**Comment by Crizz0** [comment]
Because other line endings are not allowed and your file has the wrong line endings, maybe caused by your text editor. Please convert it and push this result.

**Comment by eunaumtenhoid** [comment]
I do not know much about github, how to know which error for PR not to be accepted? because this happens with some other translations as well

**Comment by Crizz0** [comment]
Every commit has this green arrow, orange dot or red cross. Click on it, and take look at the failed tests log. This will give you the error message.

**Comment by eunaumtenhoid** [comment]
I converted, but it shows the same error

**Comment by Crizz0** [comment]
Please read this and follow the instructions: https://help.github.com/articles/dealing-with-line-endings/

Am 4. Januar 2018 22:48:57 MEZ schrieb eunaumtenhoid <notifications@github.com>:

**Pull request closed without merging**
