### PR TITLE
Arabic translation

### PR DESCRIPTION
**Pull request by alhitary**

### CODE REVIEW

**Comment by Crizz0** [comment]
Hey,

i can't read that, So i hope you double checked it. :D 

I will merge this soon and will bring it with 2.0.2. 

Regards

**Comment by alhitary** [comment]
I did checked already before i sent it.
Don't worry. 
@_@

**Comment by Crizz0** [comment]
Hehe.

**Comment by alhitary** [comment]
I wish you don't forget to merge Arabic translation @_@

**Comment by Crizz0** [comment]
It will be in 2.0.2.

**Pull request merged**
